### ISSUE TITLE
Where should we report test result for this project ?

### ISSUE THREAD

**Issue by MaelAudren** [STAMP-project/evosuite-model-seeding-tutorial#4]
#### Characteristics
- **Issue Type**: [test report]

#### Description

Where should we report test result for this project ? https://github.com/STAMP-project/evocrash-usecases-output ?

**Comment by MaelAudren** [comment]
I think that the tests results should be pushed on the following github repository: https://github.com/STAMP-project/evosuite-model-seeding-empirical-evaluation

**Comment by xdevroey** [comment]
Hi @MaelAudren, No, we use that repository for the empirical evaluation. We do not have a usecases-output repository for EvoSuite model-seeding. I have created one here: https://github.com/STAMP-project/evosuite-model-seeding-usecases-output
